"""Production behavior-cloning, DAgger, and RL fine-tuning tools."""

from rl_suspension.production.training.bc import (
    BCDatasetArrays,
    BCTrainer,
    BCTrainerConfig,
    BCTrainingResult,
    EpochMetrics,
    FileCheckpointHook,
    SelectedCheckpoint,
    ValidationLossSelector,
    concatenate_datasets,
    default_bc_loss,
)
from rl_suspension.production.training.dagger import (
    DEFAULT_BETA_SCHEDULE,
    DaggerConfig,
    DaggerResult,
    DaggerRoundReport,
    DaggerTrainer,
    SnapshotQueryQueue,
)
from rl_suspension.production.training.finetune import (
    BCRegularizationConfig,
    DecayingBCRegularizer,
    FineTuneConfig,
    FineTuneOrchestrator,
    FineTuneResult,
    PhysicalSafetyFilter,
    SafetyEvent,
    intervention_counter,
)
from rl_suspension.production.training.losses import (
    BCLossConfig,
    BCLossOutput,
    BehaviorCloningLoss,
    contiguous_action_delta_loss,
    normalize_physical_actions,
    normalized_weighted_huber_loss,
    phase_quality_weights,
)

__all__ = [
    "BCDatasetArrays",
    "BCLossConfig",
    "BCLossOutput",
    "BCRegularizationConfig",
    "BCTrainer",
    "BCTrainerConfig",
    "BCTrainingResult",
    "BehaviorCloningLoss",
    "DEFAULT_BETA_SCHEDULE",
    "DaggerConfig",
    "DaggerResult",
    "DaggerRoundReport",
    "DaggerTrainer",
    "DecayingBCRegularizer",
    "EpochMetrics",
    "FileCheckpointHook",
    "FineTuneConfig",
    "FineTuneOrchestrator",
    "FineTuneResult",
    "PhysicalSafetyFilter",
    "SafetyEvent",
    "SelectedCheckpoint",
    "SnapshotQueryQueue",
    "ValidationLossSelector",
    "concatenate_datasets",
    "contiguous_action_delta_loss",
    "default_bc_loss",
    "intervention_counter",
    "normalize_physical_actions",
    "normalized_weighted_huber_loss",
    "phase_quality_weights",
]
